/*
 * Problem: C. Dice Roll Sequence
 * Contest: 2195/C | Link: https://codeforces.com/contest/2195/problem/C
 *
 * ── Problem ──────────────────────────────────────────────
 * Consider the following cube D where numbers x and 7-x lie on opposite sides :
 * Image generated by Nano Banana Pro. A sequence b of integers from 1 to 6 is called a dice roll sequence if it satisfies the following condition:
 * 
 * • All pairs of adjacent elements lie on adjacent^(∗) sides of the cube. For example, [1,4,2] is a dice roll sequence, while [3,4,6,3] is not because 3 and 4 are not on adjacent sides of the dice. Additionally, [2,2,4] is not a dice roll sequence because 2 and 2 are on the same (not adjacent) side of the dice.
 * Given a sequence a of n integers from 1 to 6, you can perform the following operation any number of times (possibly zero).
 * 
 * • Select an index 1 ≤ i ≤ n and an integer 1 ≤ x ≤ 6. Then, change the value of a_i to x. Please determine the minimum number of operations required to make a a dice roll sequence.
 * ^(∗)Two sides of the cube S and T are called adjacent if they share exactly one edge of the cube. Do note that this condition implies S ≠ T as well.
 *
 * ── Input ────────────────────────────────────────────────
 * Each test contains multiple test cases. The first line contains the number of test cases t (1 ≤ t ≤ 10^4). The description of the test cases follows.
 * The first line of each test case contains a single integer n (1 ≤ n ≤ 3 · 10^5).
 * The second line of each test case contains n integers a_1,a_2,...,a_n (1 ≤ a_i ≤ 6).
 * It is guaranteed that the sum of n over all test cases does not exceed 3 · 10^5.
 *
 * ── Output ───────────────────────────────────────────────
 * For each test case, output the minimum number of operations required to make a a dice roll sequence.
 *
 * ── Example Input ────────────────────────────────────────
 * 3
 * 3
 * 1 4 2
 * 4
 * 3 4 6 3
 * 10
 * 6 1 4 3 1 3 2 5 4 4
 *
 * ── Example Output ───────────────────────────────────────
 * 0
 * 1
 * 4
 *
 * ── Notes ────────────────────────────────────────────────
 * For the first test case, the sequence a is [1,4,2]. As this is already a dice roll sequence, the answer is 0.
 * For the second test case, the sequence a is [3,4,6,3].
 * Changing exactly one element, you can get [3,red5,6,3], which is a dice roll sequence.
 * For the third test case, the sequence a is [6,1,4,3,1,3,2,5,4,4].
 * Changing exactly 4 elements, you can get [red5,1,4,red2,1,3,2,red1,red5,4], which is a dice roll sequence.
 *
 */

#include <bits/stdc++.h>
using namespace std;

void solve() {
    int n;
    cin >> n;
    vector<int> a(n);
    for (int i = 0; i < n; i++) {
        cin >> a[i];
    }

    vector<int> dp(7, 0);

    for (int face = 1; face <= 6; face++) {
        
        //if the face mathches what already there cost is 0 otherwise cost is 1..
        if (a[0] == face) {
            dp[face] = 0;
        } else {
            dp[face] = 1;
        }
    }

    
    for (int i = 1; i < n; i++) {
        // n_dp will hold the costs for the CURRENT dice
        vector<int> n_dp(7, 1e9); 

        for (int curr_face = 1; curr_face <= 6; curr_face++) {
           
            int cost_to_change = (a[i] == curr_face) ? 0 : 1;

            for (int prev_face = 1; prev_face <= 6; prev_face++) {
                
                if (curr_face != prev_face && curr_face + prev_face != 7) {
                    
                    n_dp[curr_face] = min(n_dp[curr_face], dp[prev_face] + cost_to_change);
                }
            }
        }
        // Move to the next step
        dp = n_dp;
    }

    //returning the min value in the dp
    int ans = 1e9;
    for (int face = 1; face <= 6; face++) {
        ans = min(ans, dp[face]);
    }
    
    cout << ans << "\n";
}

int main() {
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
    return 0;
}